name: Bug
about: Report a regression or defect
labels: [bug]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What is broken and impact.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Exact steps, commands, and inputs.
    validations:
      required: true

  - type: textarea
    id: expected_actual
    attributes:
      label: Expected vs Actual
      description: What should happen versus what happened.
    validations:
      required: true

  - type: input
    id: artifact
    attributes:
      label: Artifact
      description: Link to failing run, logs, or screenshots.
      placeholder: https://github.com/.../actions/runs/...
    validations:
      required: true
